app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');


//Route::get('/listusers', [
//    'as' => 'listusers', 'uses' => 'UserController@index'
//]);


//Usuarios
Route::resource('users', 'UserController');

//Auxiliares
Route::get('/search', [
    'as' => 'searchusers', 'uses' => 'UserController@getsearch'
]);

Route::post('/search', [
    'as' => 'searchusers', 'uses' => 'UserController@postsearch'
]);

Route::get('/materias', [
    'as' => 'materias', 'uses' => 'MateriaController@index'
]);

Route::get('help/{id}', [
    'as' => 'help', 'uses' => 'HelpController@index'
]);


//Encuesta A
Route::get('survey/a/', [
    'as' => 'iaenc', 'uses' => 'AEncController@index'
]);

Route::get('survey/a/{id}', [
    'as' => 'eaenc', 'uses' => 'AEncController@edit'
]);

Route::patch('survey/a/{id}', [
    'as' => 'saenc', 'uses' => 'AEncController@save'
]);


Route::get('survey/a/{id}/changestate', [
    'as' => 'csaenc', 'uses' => 'AEncController@grabarshow'
]);

Route::patch('survey/a/{id}/changestate', [
    'as' => 'caenc', 'uses' => 'AEncController@grabar'
]);

Route::get('survey/a/{id}/imprimir', [
    'as' => 'paenc', 'uses' => 'AEncController@imprimir'
]);

Route::post('survey/a/{id}', [
    'as' => 'naenca', 'uses' => 'AEncController@create'
]);

Route::delete('survey/a/{id}', [
    'as' => 'baenc', 'uses' => 'AEncController@borrar'
]);


//Encuesta B


Route::get('/survey/b', [
    'as' => 'ibenc', 'uses' =>'BEncController@index'
]);


Route::post('survey/b/{id}', [
    'as' => 'nbenc', 'uses' => 'BEncController@create'
]);

Route::post('survey/b/{id}/save', [
    'as' => 'sbenc', 'uses' => 'BEncController@save'
]);

Route::delete('survey/b/{id}', [
    'as' => 'bbenc', 'uses'=> 'BEncController@borrar'
]);

Route::get('survey/b/{id}/imprimir', [
    'as' => 'pbenc', 'uses' => 'BEncController@imprimir'
]);

//Encuesta C
Route::get('/survey/c', [
    'as' => 'icenc', 'uses' =>'CEncController@index'
]);

Route::post('survery/c/{id}', [
    'as' => 'ncenc', 'uses' => 'CEncController@create'
]);

Route::post('survey/c/{id}/save', [
    'as' => 'scenc', 'uses' => 'CEncController@save'
]);

Route::delete('survey/c/{id}', [
    'as' => 'cbenc', 'uses'=> 'CEncController@borrar'
]);

Route::get('survey/c/{id}/imprimir', [
    'as' => 'pcenc', 'uses' => 'CEncController@imprimir'
]);

app/User.php
<?php

namespace EncDoc;

use Illuminate\Foundation\Auth\User as Authenticatable;
//

/**
 * Class User
 *
 * @package EncDoc
 * @mixin \Eloquent
 * @property integer $id
 * @property string $name
 * @property string $dni
 * @property string $email
 * @property string $password
 * @property boolean $admin
 * @property string $remember_token
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @method static \Illuminate\Database\Query\Builder|\EncDoc\User whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\EncDoc\User whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\EncDoc\User whereDni($value)
 * @method static \Illuminate\Database\Query\Builder|\EncDoc\User whereEmail($value)
 * @method static \Illuminate\Database\Query\Builder|\EncDoc\User wherePassword($value)
 * @method static \Illuminate\Database\Query\Builder|\EncDoc\User whereAdmin($value)
 * @method static \Illuminate\Database\Query\Builder|\EncDoc\User whereRememberToken($value)
 * @method static \Illuminate\Database\Query\Builder|\EncDoc\User whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\EncDoc\User whereUpdatedAt($value)
 * @property-read \EncDoc\AEnc $aenc
 * @property-read \Illuminate\Database\Eloquent\Collection|\EncDoc\BEnc[] $benc
 */
class User extends Authenticatable
{
    protected $table = 'users';
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'dni', 'admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function aenc()
    {
        return $this->hasMany('\EncDoc\AEnc');
    }

    public function benc()
    {
        return $this->hasMany('\EncDoc\BEnc');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace EncDoc\Http\Controllers;

use EncDoc\User;
use Illuminate\Http\Request;

use EncDoc\Http\Requests;
use Illuminate\Support\Facades\Auth;


class UserController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * List all Users
     */
    public function index()
    {
        if (Auth::user()->admin) {
            $users = User::orderBy('name')->paginate();
            return view('users/index', compact('users'));

        } else {

            return redirect('/home');
        }
    }

    public function create()
    {
        if (Auth::user()->admin) {
            return view('users.create');
        } else {
            return redirect('/home');
        }

    }

    public function getsearch()
    {
        return view('users.search');
    }

    public function postsearch(Request $request)
    {
        $users = User::where('name', 'LIKE', '%' . $request->name . '%')->paginate();
        //dd($users);
        return view('users/index', compact('users'));
    }

    public function show(){

    }

    public function store(Request $request) {

        if (! Auth::user()->admin)
            return redirect('/home');


        /*
        $rules = array(
            'name'             => 'required',                        // just a normal required validation
            'email'            => 'required|email|unique:users',     // required and must be unique in the ducks table
            'password'         => 'required',
            'dni' => 'required|same:password'           // required and has to match the password field
        );
        */
        $rules = [ 'name'      => ['required', 'max:50'],
                    'email'    => ['required', 'email', 'unique:users'],
                    'password' => ['required', 'min:6',
                                   'regex:/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$/'],
                    'dni'      => ['required', 'numeric','digits_between:8,8']
                 ];

        $this->validate($request,$rules);

        //dd($request->all());
        $password = $request->password;

        $uservalid = new User;
        $uservalid->name = $request->name;
        $uservalid->email = $request->email;
        $uservalid->password = bcrypt($password);
        $uservalid->dni = $request->dni;
        $uservalid->admin = false;

        \Session::flash('flash_message', "Usuario : " . $uservalid->name . " Agregado correctamente");

        $uservalid->save();

        return redirect( route('users.index'));
    }
    
    public function edit($id)
    {

        if (! \Auth::user()->admin) {
            return redirect('/home');
        }

        $user = User::findOrFail($id);

        
        if(is_null($user)){
            return redirect( route('users.index'));
        }

        return view('users.edit', compact('user'));
    }

    public function update($id, Request $request)
    {
        if (! \Auth::user()->admin)
            return redirect('/home');

        $user = User::findOrFail($id);

        $rules = [ 'name'     => ['required', 'max:50'],
                   'email'    => ['required', 'email'],
                   'password' => ['min:6',
                                 'regex:/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$/'],
                   'dni'      => ['required', 'numeric','digits_between:8,8']
        ];

        $this->validate($request,$rules);

        $password = $request->password;

        $user->name = $request->name;
        $user->email = $request->email;

        if ($password != "") {
            $user->password = bcrypt($password);
        }

        $user->dni = $request->dni;

        $user->save();

        \Session::flash('flash_message', 'Registro actualizado exitósamente');

        return \Redirect::route('users.index');
    }

    public function destroy($id, Request $request)
    {
        if (! \Auth::user()->admin) {
            return redirect('/home');
        }


        $user = User::findOrFail($id);

        $message = $user->name . ' fue eliminado';

        $user->delete();

        if ($request->ajax()) {
            return \Response::json([
                'id' => $user->id,
                'message' => $message
            ]);
        }
        \Session::flash('message',$message);
        return \Redirect::route('users.index');
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                Crear Usuario
            </div>
                <div class="panel-body">
                    @include('partials.errors')
                    {!! Form::open(['url' =>  route('users.store'),  'method' => 'post' ])  !!}
                    <div class="form-group">
                        {!! Form::label('name', 'Nombre Completo', ['class' => 'control-label']) !!}
                        {!! Form::text('name', old('name'),
                                        ['required',
                                         'class' => 'form-control',
                                         'placeholder' => 'Apelllido y Nombre'
                                        ])
                        !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('dni', 'D.N.I.', ['class' => 'control-label']) !!}
                        {!! Form::number('dni', old('dni'),
                                    ['require',
                                     'class' => 'form-control',
                                     'placeholder' => '99999999',
                                     'min' => '1000000',
                                     'max' => '99999999'
                                     ])
                        !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('email', 'Correo Electrónico', ['class' => 'control-label']) !!}
                        {!! Form::email('email', $value = old('email'),
                                        $attributes = ['required', 'class' => 'form-control',
                                                       'placeholder' => 'usuario@ejemplo.com'] )
                        !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('password', 'Clave', ['class' => 'control-label']) !!}
                        {!! Form::password('password',
                                            ['required',
                                             'class' => 'form-control',
                                             'placeholder' => '********'
                                            ])
                         !!}
                        <p class="help-block">La clave debe ser como mínimo de 6 caracteres. Tener algún dígito y alguna
                        mayúscula</p>
                        <p class="help-block">Todos los Campos son Requeridos</p>
                    </div>
                    <button type="submit" class="btn btn-default glyphicon glyphicon-save">Grabar</button>
                    </form>
                </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                Editar Usuarios
            </div>
                <div class="panel-body">
                    @include('partials.errors')
                    {!! Form::open(['url' =>  route('users.update', ['id' => $user->id]),  'method' => 'patch' ])  !!}
                    <div class="form-group">
                        {!! Form::label('name', 'Nombre Completo', ['class' => 'control-label']) !!}
                        {!! Form::text('name', $user->name,
                                        ['required',
                                         'class' => 'form-control',
                                         'placeholder' => 'Apelllido y Nombre'
                                        ])
                        !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('dni', 'D.N.I.', ['class' => 'control-label']) !!}
                        {!! Form::number('dni', $user->dni,
                                    ['require',
                                     'class' => 'form-control',
                                     'placeholder' => '99999999',
                                     'min' => '1000000',
                                     'max' => '99999999'
                                     ])
                        !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('email', 'Correo Electrónico', ['class' => 'control-label']) !!}
                        {!! Form::email('email', $value = $user->email,
                                        $attributes = ['required', 'class' => 'form-control',
                                                       'placeholder' => 'usuario@ejemplo.com'] )
                        !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('password', 'Clave', ['class' => 'control-label']) !!}
                        {!! Form::password('password',
                                            [
                                             'class' => 'form-control',
                                             'placeholder' => '********'
                                            ])
                         !!}
                        <p class="help-block">La clave debe ser como mínimo de 6 caracteres. Tener algún dígito y alguna
                        mayúscula</p>
                        <p class="help-block">Todos los Campos son Requeridos</p>
                    </div>
                    <button type="submit" class="btn btn-default glyphicon glyphicon-save">Grabar</button>
                    </form>
                </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                Listado de Usuarios - Orden Alfabético
            </div>
                <div class="panel-body">
                    @if(Session::has('flash_message'))
                        <div class="alert alert-success"><em> {!! session('flash_message') !!}</em></div>
                    @endif
                    <p>
                        @if(Auth::user()->admin)
                            <a class="btn btn-info glyphicon glyphicon-user"
                               href="{{ route('users.create') }}" role="button"> Nuevo Usuario </a>
                        @endif
                        <a class="btn btn-info glyphicon glyphicon-search" href="{{ route('searchusers') }}" role="button"> Buscar </a>
                    </p>

                    <table class="table">
                    <thead class="thead-inverse">
                        <tr>
                            <th>Nombre</th>
                            <th>DNI</th>
                            @if(Auth::user()->admin)<th>Email</th>@endif
                            @if(Auth::user()->admin)<th>Acciones</th>@endif
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $user)
                        <tr data-id="{{ $user->id }}">
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->dni }}</td>
                            @if(Auth::user()->admin)<td>{{ $user->email }}</td>@endif
                            @if(Auth::user()->admin)<td>
                                <a href="{{ route('users.edit', ['id' => $user->id]) }}"> Editar</a>
                                <a href="#!" class="btn-delete"> Borrar</a>
                                Informe
                            </td>@endif
                        </tr>
                        @endforeach
                    </tbody>
                    </table>
                    {!! $users->render() !!}
                </div>
        </div>
    </div>
    {!! Form::open(['route' => ['users.destroy', ':USER_ID'], 'method' => 'DELETE', 'id' => 'form-delete']) !!}
    {!! Form::close() !!}
@endsection

@section('scripts')
<script>
    $(document).ready(function () {
        $('.btn-delete').click(function(e){

            e.preventDefault();

            var row = $(this).parents('tr');
            var id = row.data('id');
            var form = $('#form-delete');
            var url = form.attr('action').replace(':USER_ID', id);
            var data = form.serialize();



            $.post(url, data, function(result) {
                row.fadeOut();
                alert(result.message);
            }).fail(function () {
                alert('El usuario no fue eliminado');
                row.show();
            })
        });
    });
</script>
@endsection

resources/views/users/search.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Crear Usuario
                </div>
                <div class="panel-body">
                    @include('partials.errors')
                    {!! Form::open(['url' =>  route('searchusers'),  'method' => 'post' ])  !!}
                    <div class="form-group">
                        {!! Form::label('name', 'Texto parcial del Nombre', ['class' => 'control-label']) !!}
                        {!! Form::text('name', old('name'),
                                        ['required',
                                         'class' => 'form-control',
                                         'placeholder' => 'Nombre a buscar'
                                        ])
                        !!}
                    </div>
                        <p class="help-block">Ingrese parte del nombre a buscar.</p>
                    </div>
                    <button type="submit" class="btn btn-default glyphicon glyphicon-search">Buscar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection